"""add mobile number and driver profile

Revision ID: 92008dbc892f
Revises: ae9f7cd4f194
Create Date: 2026-01-08 18:13:30.690106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92008dbc892f'
down_revision: Union[str, Sequence[str], None] = 'ae9f7cd4f194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column(
        'users',
        sa.Column(
            'mobile_number',
            sa.String(length=20),
            nullable=False,
            server_default='0000000000',
        ),
    )
    op.alter_column('users', 'mobile_number', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mobile_number')
    op.drop_table('driver_profiles')
    # ### end Alembic commands ###
