from app.constants.roles import SUPER_ADMIN, ADMIN, RETAILER, CUSTOMER, GUEST, SUPPORT

CAN_MANAGE_PRODUCTS = [SUPER_ADMIN, ADMIN, RETAILER]
CAN_VIEW_PRODUCTS = [SUPER_ADMIN, ADMIN, RETAILER, CUSTOMER, GUEST, SUPPORT]